FROM rocker/verse:latest

RUN /rocker_scripts/install_quarto.sh

 RUN tlmgr update --all --self \
  && tlmgr install pdfcol unicode-math booktabs caption float tcolorbox pgf environ soul gdal terra \
  && tlmgr path add || true

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  libcurl4-openssl-dev libglpk-dev \
  && rm -rf /var/lib/apt/lists/* \
  && R -q -e 'install.packages(c("iNEXT", "bold", "janitor", "countrycode", "taxize", "here", "vegan", "broom.mixed", "lme4"))'

WORKDIR /home/rstudio